### PR TITLE
Fix delegate sponsor proposal for members with delegated voting power

### LINKED ISSUE #158: Members delegating shares should not be able to sponsor
# Description

Sponsor logic should look at delegated shares.

If a member is delegating shares they should not be able to sponsor, unless someone else is delegating to them.

### PR DESCRIPTION
**Pull request by santteegt**
## GitHub Issue

Fixes #158 

## Changes

Sponsor proposal is disabled if a member has delegated his voting power and does not have any voting delegated to him

## Packages Added

None

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs locally
- [X] App builds locally (run the build command for _any impacted package_ and check for any errors before the PR)

### CODE REVIEW

**Review by 0xRowdy — APPROVED** [review]

File: apps/admin/src/components/proposalCards/Unsponsored.tsx [hunk 1]
```diff
@@ -109,6 +109,18 @@ export const Unsponsored = ({
       ? true
       : 'You are not connected to the same network as the DAO';
 
+  const notDelegating = useMemo(() => {
```
Comment (0xRowdy) [inline apps/admin/src/components/proposalCards/Unsponsored.tsx:112]: Just a suggestion based on my preference but definitely not required
  const isNotDelegating = useMemo(() => {
```

**Review by skuhlmann — APPROVED** [review]
